package attestation;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan
 */
public class AssignerEnseignantsFrame extends javax.swing.JFrame {

    private AffectationEnseignants affectationEnseignants;
    private ArrayList<String> Donnees;
    private ArrayList<String> enseignantsSelectionnes;
    private String nomClasse;
    private int k=-1,l=-1,m=-1,n=-1,o=-1,p=-1,q=-1,r=-1,s=-1,t=-1,v=-1,w = -1;

    /** Creates new form AssignerEnseignantsFrame */
    public AssignerEnseignantsFrame(String nomClasse) {
        initComponents();
        setTitle("Affectation des enseignants");
        setVisible(true);
        setLocationRelativeTo(null);

        affectationEnseignants = new AffectationEnseignants();
        Donnees = new ArrayList<String>();
        enseignantsSelectionnes = new ArrayList<String>();
        this.nomClasse = nomClasse;

        jLabel1.setText(nomClasse);

        Donnees = affectationEnseignants.recupererEnseignants();
        for(int i = 0; i < Donnees.size(); i = i+3)
        {
            if(Donnees.get(i).equals("FRANCAIS")) jComboBox1.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("ANGLAIS") || Donnees.get(i).equals("ALLEMAND") || Donnees.get(i).equals("ITALIEN") || Donnees.get(i).equals("ESPAGNOL")) jComboBox2.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("ANGLAIS") || Donnees.get(i).equals("ALLEMAND") || Donnees.get(i).equals("ITALIEN") || Donnees.get(i).equals("ESPAGNOL")) jComboBox3.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("HISTOIRE-GEO")) jComboBox4.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("MATHEMATIQUES")) jComboBox5.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("SVT")) jComboBox6.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("TECHNOLOGIE")) jComboBox7.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("SCIENCES_PHYSIQUES")) jComboBox8.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("EPS")) jComboBox9.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("EDUCATION_MUSICALE")) jComboBox10.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
            if(Donnees.get(i).equals("ARTS_PLASTIQUES")) jComboBox11.addItem(Donnees.get(i+1)+" "+Donnees.get(i+2));
        }

        Donnees = affectationEnseignants.afficherEnseignantsAssignes(null, nomClasse);
        for(int j = 0; j < Donnees.size(); j = j + 4)
        {
            jComboBox12.addItem(Donnees.get(j+1)+" "+Donnees.get(j+2));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("CLASSE");

        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("FRANCAIS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("LV1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("LV2");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("HISTOIRE - GEO");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("MATHEMATIQUES");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("SVT");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("TECHNOLOGIE");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setText("SCIENCES PHYSIQUES");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("EPS");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("EDUCATION MUSICALE");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(153, 153, 255));
        jLabel12.setText("ARTS PLASTIQUES");

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(153, 153, 255));
        jLabel13.setText("P P");

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });

        jButton1.setText("VALIDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 164, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(11, 11, 11)
                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(k == -1)
        {
            enseignantsSelectionnes.add(jComboBox1.getSelectedItem().toString());
            k = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(k);
            enseignantsSelectionnes.add(jComboBox1.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(l == -1)
        {
            enseignantsSelectionnes.add(jComboBox2.getSelectedItem().toString());
            l = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(l);
            enseignantsSelectionnes.add(jComboBox2.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(m == -1)
        {
            enseignantsSelectionnes.add(jComboBox3.getSelectedItem().toString());
            m = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(m);
            enseignantsSelectionnes.add(jComboBox3.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if(n == -1)
        {
            enseignantsSelectionnes.add(jComboBox4.getSelectedItem().toString());
            n = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(n);
            enseignantsSelectionnes.add(jComboBox4.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        if(o == -1)
        {
            enseignantsSelectionnes.add(jComboBox5.getSelectedItem().toString());
            o = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(o);
            enseignantsSelectionnes.add(jComboBox5.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        if(p == -1)
        {
            enseignantsSelectionnes.add(jComboBox6.getSelectedItem().toString());
            p = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(p);
            enseignantsSelectionnes.add(jComboBox6.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        if(q == -1)
        {
            enseignantsSelectionnes.add(jComboBox7.getSelectedItem().toString());
            q = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(q);
            enseignantsSelectionnes.add(jComboBox7.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        if(r == -1)
        {
            enseignantsSelectionnes.add(jComboBox8.getSelectedItem().toString());
            r = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(r);
            enseignantsSelectionnes.add(jComboBox8.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        if(s == -1)
        {
            enseignantsSelectionnes.add(jComboBox9.getSelectedItem().toString());
            s = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(s);
            enseignantsSelectionnes.add(jComboBox9.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        if(t == -1)
        {
            enseignantsSelectionnes.add(jComboBox10.getSelectedItem().toString());
            t = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(t);
            enseignantsSelectionnes.add(jComboBox10.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        if(v == -1)
        {
            enseignantsSelectionnes.add(jComboBox11.getSelectedItem().toString());
            v = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(v);
            enseignantsSelectionnes.add(jComboBox11.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        if(w == -1)
        {
            enseignantsSelectionnes.add("PP");
            enseignantsSelectionnes.add(jComboBox12.getSelectedItem().toString());
            w = (enseignantsSelectionnes.size()-1);
        }
        else
        {
            enseignantsSelectionnes.remove(w-1);
            enseignantsSelectionnes.remove(w-1);
            enseignantsSelectionnes.add("PP");
            enseignantsSelectionnes.add(jComboBox12.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        affectationEnseignants.affecterEnseignant(nomClasse, enseignantsSelectionnes);
        dispose();
        JOptionPane.showMessageDialog(null, "Les enseignants ont bien été affectés à la classe", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
