package attestation;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author nathan
 */
public class FicheFrame extends javax.swing.JFrame {

    private Fiche fiche;
    private ArrayList<Integer> idCategorie;
    private String Lognom;
    private String Logprenom;
    private String nomEleve;
    private String prenomEleve;
    private String Matiere;
    private String Classe;
    private String PP;
    private java.awt.event.MouseEvent Evt;

    /** Creates new form FicheFrame */
    public FicheFrame(String Lognom,String Logprenom, String nomEleve, String prenomEleve, String Matiere, String Classe, String PP) {
        initComponents();
        setTitle("Socle commun des connaissances et des compétences");
        //setSize(700,663);
        setVisible(true);
        setLocationRelativeTo(null);

        fiche = new Fiche(nomEleve,prenomEleve,jLabel6,jTable1);
        idCategorie = new ArrayList<Integer>();
        this.Lognom = Lognom;
        this.Logprenom = Logprenom;
        this.nomEleve = nomEleve;
        this.prenomEleve = prenomEleve;
        this.Matiere = Matiere;
        this.Classe = Classe;
        this.PP = PP;

        jLabel2.setText("<html><b><u>MATIERE :</u></b> "+Matiere+"</html>");
        jLabel3.setText("<html><b><u>NOM :</u></b> "+nomEleve+"</html>");
        jLabel4.setText("<html><b><u>PRENOM :</u></b> "+prenomEleve+"</html>");
        jLabel5.setText("<html><b><u>CLASSE :</u></b> "+Classe+"</html>");
        jLabel8.setText("<html><u>Identifiant :</u> "+Lognom+" "+Logprenom+"</html>");

        jMenuItem3.setEnabled(false);
        if(PP.equals("oui"))    jMenuItem4.setEnabled(true);
        else jMenuItem4.setEnabled(false);

        fiche.recupererFiche(Matiere);
        idCategorie.add(0);
        fiche.setIdCategorie(idCategorie);
        fiche.afficherChamps(0);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("SOCLE COMMUN DES CONNAISSANCES ET DES COMPETENCES");

        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("NOM:");

        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Prénom:");

        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("Catégorie");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Consigne", "Valide"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setForeground(new java.awt.Color(204, 102, 0));
        jButton1.setText("Suivant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(204, 102, 0));
        jButton2.setText("Précédent");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Pour valider une consigne, selectionnez la ligne correspondante");

        jButton3.setForeground(new java.awt.Color(204, 102, 0));
        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Enseignant:");

        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Matiere");

        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Classe");

        jMenu1.setText("Fichier");

        jMenuItem2.setText("Retourner au Menu Principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Se deconnecter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Fiches");

        jMenuItem3.setText("Matière");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Professeur Principal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("BII");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(320, 320, 320)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton2)
                                .addGap(136, 136, 136)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton2.setEnabled(true);       
        fiche.setNbreClic(fiche.getNbreClic() + 1);
        
        idCategorie.add(fiche.getIdNextCategorie());
        fiche.setIdCategorie(idCategorie);
        fiche.setConsigneSelectionneeMult(new ArrayList<String>());
        fiche.afficherChamps(fiche.getIdCategorie().get(fiche.getNbreClic()));
        fiche.setKeyCount(0);
        if(fiche.getIdNextCategorie() + fiche.Count()*4 == fiche.getDonnees().size()) jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton1.setEnabled(true);        
        idCategorie.remove(fiche.getNbreClic());
        fiche.setIdCategorie(idCategorie);
        fiche.setConsigneSelectionneeMult(new ArrayList<String>());
        fiche.setNbreClic(fiche.getNbreClic() - 1);

        fiche.afficherChamps(fiche.getIdCategorie().get(fiche.getNbreClic()));
        fiche.setKeyCount(0);
        if(fiche.getNbreClic() == 0) jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int choix = JOptionPane.showConfirmDialog(null,"Souhaitez-vous vraiment valider?","Validation", JOptionPane.YES_NO_OPTION);

        if(choix == JOptionPane.YES_OPTION)
        {
            fiche.validerChamps(nomEleve,prenomEleve,Matiere,Classe);
            fiche.setKeyCount(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new MenuEnseignantFrame(Lognom,Logprenom,Matiere);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int choix = JOptionPane.showConfirmDialog(null,"Souhaitez-vous vraiment vous deconnecter?","Validation", JOptionPane.YES_NO_OPTION);

        if(choix == JOptionPane.YES_OPTION)
        {
            dispose();
            new ConnexionFrame();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            Matiere = jLabel2.getText().toString().substring(30,jLabel2.getText().toString().length() - 7);
            fiche.recupererFiche(Matiere);
            idCategorie.clear();
            idCategorie.add(0);
            fiche.setIdCategorie(idCategorie);
            fiche.setConsigneSelectionneeMult(new ArrayList<String>());
            fiche.setNbreClic(0);
            fiche.setKeyCount(0);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
            fiche.afficherChamps(idCategorie.get(0));
            if(PP.equals("oui"))    jMenuItem4.setEnabled(true);
            else jMenuItem4.setEnabled(false);
            jMenuItem3.setEnabled(false);
            jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
            Matiere = "PP";
            fiche.recupererFiche(Matiere);
            idCategorie.clear();
            idCategorie.add(0);
            fiche.setIdCategorie(idCategorie);
            fiche.setConsigneSelectionneeMult(new ArrayList<String>());
            fiche.setNbreClic(0);
            fiche.setKeyCount(0);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
            fiche.afficherChamps(0);
            jMenuItem4.setEnabled(false);
            jMenuItem3.setEnabled(true);
            jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            Matiere = "BII";
            fiche.recupererFiche(Matiere);
            idCategorie.clear();
            idCategorie.add(0);
            fiche.setIdCategorie(idCategorie);
            fiche.setConsigneSelectionneeMult(new ArrayList<String>());
            fiche.setNbreClic(0);
            fiche.setKeyCount(0);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
            fiche.afficherChamps(idCategorie.get(0));
            if(PP.equals("oui"))    jMenuItem4.setEnabled(true);
            else jMenuItem4.setEnabled(false);
            jMenuItem3.setEnabled(true);
            jMenuItem5.setEnabled(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode() == 38)
        {
            fiche.setKeyCount(fiche.getKeyCount() - 1);
            fiche.getKeyPressed(Evt, evt.getKeyCode());
        } 
        else if(evt.getKeyCode() == 40)
        {
            fiche.setKeyCount(fiche.getKeyCount() + 1);
            fiche.getKeyPressed( Evt, evt.getKeyCode());
        }
}//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Evt = evt;
        fiche.getMouseClicked(evt);
}//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
