package attestation;
import java.io.*;
import java.util.ArrayList;

/**
 *
 * @author Nathan
 */
public class ImporterFichierFrame extends javax.swing.JFrame {

    private TraitementImportation traitement;

    /** Creates new form ImporterFichierFrame */
    public ImporterFichierFrame() {
        initComponents();
        setTitle("Ouvrir fichier");
        setVisible(true);
        setLocationRelativeTo(null);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
   try
   {
       ArrayList<String> Donnees = new ArrayList<String>();
       String monFichier= null;
       String ligne=new String();

       if(evt.getActionCommand().equals("ApproveSelection"))
       {
           monFichier = jFileChooser1.getSelectedFile().toString();
           
           InputStream ips=new FileInputStream(new File(monFichier));
           InputStreamReader ipsr=new InputStreamReader(ips);
           BufferedReader br=new BufferedReader(ipsr);

           while((ligne=br.readLine())!=null)
           {
               Donnees.add(ligne);
           }

           br.close();
           traitement = new TraitementImportation(Donnees);
           traitement.filtreEleves();
           dispose();
       }
       else dispose();
    }
    catch(java.io.FileNotFoundException e){}
    catch (java.io.IOException e) {}
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

}
