package attestation;
import javax.swing.JOptionPane;

/**
 *
 * @author nathan
 */
public class MenuEnseignantFrame extends javax.swing.JFrame {

    private Enseignant enseignant;
    private String Lognom;
    private String Logprenom;
    private String Matiere;
    private int nbreClic;
    private java.awt.event.MouseEvent Evt;

    /** Creates new form MenuEnseignantFrame */
    public MenuEnseignantFrame(String Lognom,String Logprenom, String Matiere) {
        initComponents();
        setTitle("Menu Enseignant");
        setSize(700,600);
        setVisible(true);
        setLocationRelativeTo(null);

        enseignant = new Enseignant();
        this.Lognom = Lognom;
        this.Logprenom = Logprenom;
        this.Matiere = Matiere;
        nbreClic = 0;

        jLabel1.setText("<html><u><b>MENU ENSEIGNANT</b></u></html>");
        jLabel2.setText("<html><u>Identifiant :</u> "+Lognom+" "+Logprenom+"</html>");
        jLabel3.setText("<html><u>Matière :</u> "+Matiere+"</html>");

        enseignant.afficherClasses(jTable1,Lognom,Logprenom);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("MENU ENSEIGNANT");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("identifiant : ");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("matiere : ");

        jTable1.setForeground(new java.awt.Color(217, 34, 34));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "P P"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Veuillez sélectionner la classe sur laquelle vous souhaitez travailler:");

        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Suivant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Précédent");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Se deconnecter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(632, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jButton2)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(256, 256, 256))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Evt = evt;
        enseignant.getMouseClicked(jTable1,evt,nbreClic);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nbreClic ++;
        if(nbreClic % 2 != 0)
        {
            if(enseignant.getClasseSelectionnee().length() != 0)
            {
                jButton2.setEnabled(true);
                jLabel4.setText("Veuillez sélectionner l'élève sur lequel vous souhaitez travailler:");
                enseignant.afficherEleves(jTable1);
                enseignant.setKeyCount(0);
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Veuillez selectionner une classe.","Information", JOptionPane.INFORMATION_MESSAGE);
                nbreClic --;
            }
        }
        else
        {
           if(enseignant.getNomEleve().length() != 0)
           {
            dispose();
            new FicheFrame(Lognom,Logprenom,enseignant.getNomEleve(),enseignant.getPrenomEleve(),Matiere,enseignant.getClasseSelectionnee(),enseignant.getPP());
           }
           else 
           {
               JOptionPane.showMessageDialog(null,"Veuillez selectionner un élève.","Information", JOptionPane.INFORMATION_MESSAGE);
               nbreClic --;
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setEnabled(false);
        enseignant.setKeyCount(0);
        nbreClic --;      
        jLabel4.setText("<html><b>Veuillez sélectionner la classe sur laquelle vous souhaitez travailler:</b></html>");
        enseignant.afficherClasses(jTable1,Lognom,Logprenom);
        enseignant.setClasseSelectionnee("");
        enseignant.setNomEleve("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int choix = JOptionPane.showConfirmDialog(null,"Souhaitez-vous vraiment vous deconnecter?","Deconnexion", JOptionPane.YES_NO_OPTION);
        
        if(choix == JOptionPane.YES_OPTION)
        {
            dispose();
            new ConnexionFrame();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        //  38 HAUT     40 BAS
        if(evt.getKeyCode() == 38)
        {

            enseignant.setKeyCount(enseignant.getKeyCount() - 1);
            enseignant.getKeyPressed(jTable1, Evt, nbreClic,38);
        }
        else if(evt.getKeyCode() == 40)
        {
            enseignant.setKeyCount(enseignant.getKeyCount() + 1);
            enseignant.getKeyPressed(jTable1, Evt, nbreClic,40);
        }
        
        /*if(evt.getKeyCode() == 10 && nbreClic % 2 == 0)
        {
            nbreClic ++;  
            jButton2.setEnabled(true);
            //enseignant.setKeyCount(0);
            enseignant.afficherEleves(jTable1);                                               // ESSAYER DE RESOUDRE ! ! !
        }
        else if(evt.getKeyCode() == 10)
        {
            dispose();
            new FicheFrame(Lognom,Logprenom,enseignant.getNomEleve(),enseignant.getPrenomEleve(),Matiere,enseignant.getClasseSelectionnee(),enseignant.getPP());
        }*/
    }//GEN-LAST:event_jTable1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
